# Data Manupilation

## NumPy

In [1]:
import numpy as np

In [6]:
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']


In [7]:
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(mat)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [8]:
vec1 = np.arange(0, 12)
vec2 = vec1.reshape(4, 3)
print(vec2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
vec1 = np.linspace(20,50,4)
vec2 = np.linspace(100,120,3)
print(vec1 + vec2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [14]:
vec = np.arange(2,5,1)
print(1/vec)
print(vec**2)

[0.5        0.33333333 0.25      ]
[ 4  9 16]


In [16]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.eye(2)
print(mat1, mat2)

[[1 2]
 [3 4]] [[1. 0.]
 [0. 1.]]


In [19]:
mat1 = np.arange(-9,0,1).reshape(3,3)
print(mat1)
print(np.min(mat1))
print(np.max(mat1))

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
-9
-1


In [31]:
matrix = np.arange(1,10).reshape(3,3)
matrix[1:3,0:3] = 0
print(matrix)

[[1 2 3]
 [0 0 0]
 [0 0 0]]


In [36]:
matrix = np.arange(1,17).reshape(4,4)
print(matrix[1:3,2:4])

[[ 7  8]
 [11 12]]


In [38]:
array = np.arange(1, 10).reshape(3, 3)
np.save('my_array.npy', array)

In [40]:
loaded_array = np.load('my_array.npy')
print(loaded_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Panda

In [2]:
import pandas as pd

In [4]:
print(pd.DataFrame())


Empty DataFrame
Columns: []
Index: []


In [12]:
data = {
'name': ['Xavier', 'Ann', 'Jana', 'Yi', 'Robin', 'Amal', 'Nori'],
'city': ['Mexico City', 'Toronto', 'Prague', 'Shanghai','Manchester', 'Cairo', 'Osaka'],
'age': [41, 28, 33, 34, 38, 31, 37],
'py-score': [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
}
row_labels = [101, 102, 103, 104, 105, 106, 107]
df = pd.DataFrame(data=data, index=row_labels)
df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

In [8]:
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] #temperature in degree Celsius
temp_data = pd.Series(temperature, index=day)
temp_data

day1    31
day2    28
day3    30
day4    32
dtype: int64

In [7]:
temp_data['day3']

30

In [11]:
temp_data[2:]

day3    30
day4    32
dtype: int64

In [13]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data

day  calories  duration_min
0  day1       450            30
1  day2       300            25
2  day3       345            29
3  day4       520            39
4  day5       600            48

In [14]:
calorie_data[:2]

day  calories  duration_min
0  day1       450            30
1  day2       300            25

In [15]:
calorie_data['calories']

0    450
1    300
2    345
3    520
4    600
Name: calories, dtype: int64

In [16]:
calorie_data[::2]

day  calories  duration_min
0  day1       450            30
2  day3       345            29
4  day5       600            48

In [20]:
calorie_data.loc[0]

day             day1
calories         450
duration_min      30
Name: 0, dtype: object

In [21]:
calorie_data.loc[[1,2],['calories']]

calories
1       300
2       345

In [22]:
calorie_data.iloc[[1,2],[1]]

calories
1       300
2       345

In [23]:
calorie_data.loc[calorie_data['calories']>500]

day  calories  duration_min
3  day4       520            39
4  day5       600            48

In [26]:
import datetime
date = datetime.date(2022, 1, 29)
print(date)

2022-01-29


In [28]:
bucket = [3.14, 'pi', 2.718]

a = pd.Series(bucket)
a

0     3.14
1       pi
2    2.718
dtype: object

In [29]:
df = pd.DataFrame({
    "Age": [25, 34, 45, 29, 52],
    "Sex": ["Male", "Female", "Male", "Female", "Male"],
    "Job": ["Skilled", "Unskilled & Non-resident", "Highly Skilled", "Skilled", "Unskilled & Non-resident"],
    "Housing": ["Own", "Rent", "Free", "Own", "Rent"],
    "Saving accounts": ["Little", "Moderate", "Rich", "Quite Rich", "Moderate"],
    "Checking account": ["Little", "Moderate", "Rich", "Moderate", "Little"],
    "Credit amount": [5000, 10000, 15000, 8000, 12000],
    "Purpose": ["Car", "Education", "Business", "Furniture/Equipment", "Vacation/Others"]
})

df.to_csv('data.csv',index=False)

In [34]:
value = df.iloc[3, 4]
value

'Quite Rich'

In [35]:
age_filtered = df['Age'] > 23
age_filtered

0    True
1    True
2    True
3    True
4    True
Name: Age, dtype: bool

In [41]:
result = df[age_filtered]
result

Age     Sex                       Job Housing Saving accounts  \
0   25    Male                   Skilled     Own          Little   
1   34  Female  Unskilled & Non-resident    Rent        Moderate   
2   45    Male            Highly Skilled    Free            Rich   
3   29  Female                   Skilled     Own      Quite Rich   
4   52    Male  Unskilled & Non-resident    Rent        Moderate   

  Checking account  Credit amount              Purpose  result  
0           Little           5000                  Car    True  
1         Moderate          10000            Education    True  
2             Rich          15000             Business    True  
3         Moderate           8000  Furniture/Equipment    True  
4           Little          12000      Vacation/Others    True

In [42]:
mean = df['Age'].mean()
mean

37.0

In [45]:
min_amount = df['Credit amount'].min()
min_amount

5000

In [49]:
group = df.groupby('Sex')
min_age = group['Age'].min()
min_age

In [50]:
merged = pd.merge(df, df, on='Sex', how='inner')
merged

Age_x     Sex                     Job_x Housing_x Saving accounts_x  \
0      25    Male                   Skilled       Own            Little   
1      25    Male                   Skilled       Own            Little   
2      25    Male                   Skilled       Own            Little   
3      34  Female  Unskilled & Non-resident      Rent          Moderate   
4      34  Female  Unskilled & Non-resident      Rent          Moderate   
5      45    Male            Highly Skilled      Free              Rich   
6      45    Male            Highly Skilled      Free              Rich   
7      45    Male            Highly Skilled      Free              Rich   
8      29  Female                   Skilled       Own        Quite Rich   
9      29  Female                   Skilled       Own        Quite Rich   
10     52    Male  Unskilled & Non-resident      Rent          Moderate   
11     52    Male  Unskilled & Non-resident      Rent          Moderate   
12     52    Male  Unskilled & Non-resident      Rent          Moderate   

   Checking account_x  Credit amount_x            Purpose_x  result_x  Age_y  \
0              Little             5000                  Car      True     25   
1              Little             5000                  Car      True     45   
2              Little             5000                  Car      True     52   
3            Moderate            10000            Education      True     34   
4            Moderate            10000            Education      True     29   
5                Rich            15000             Business      True     25   
6                Rich            15000             Business      True     45   
7                Rich            15000             Business      True     52   
8            Moderate             8000  Furniture/Equipment      True     34   
9            Moderate             8000  Furniture/Equipment      True     29   
10             Little            12000      Vacation/Others      True     25   
11             Little            12000      Vacation/Others      True     45   
12             Little            12000      Vacation/Others      True     52   

                       Job_y Housing_y Saving accounts_y Checking account_y  \
0                    Skilled       Own            Little             Little   
1             Highly Skilled      Free              Rich               Rich   
2   Unskilled & Non-resident      Rent          Moderate             Little   
3   Unskilled & Non-resident      Rent          Moderate           Moderate   
4                    Skilled       Own        Quite Rich           Moderate   
5                    Skilled       Own            Little             Little   
6             Highly Skilled      Free              Rich               Rich   
7   Unskilled & Non-resident      Rent          Moderate             Little   
8   Unskilled & Non-resident      Rent          Moderate           Moderate   
9                    Skilled       Own        Quite Rich           Moderate   
10                   Skilled       Own            Little             Little   
11            Highly Skilled      Free              Rich               Rich   
12  Unskilled & Non-resident      Rent          Moderate             Little   

    Credit amount_y            Purpose_y  result_y  
0              5000                  Car      True  
1             15000             Business      True  
2             12000      Vacation/Others      True  
3             10000            Education      True  
4              8000  Furniture/Equipment      True  
5              5000                  Car      True  
6             15000             Business      True  
7             12000      Vacation/Others      True  
8             10000            Education      True  
9              8000  Furniture/Equipment      True  
10             5000                  Car      True  
11            15000             Business      True  
12            12000      Vacation/Ot

In [59]:
data = [200, 450, 150, 400, 500, 700]

sales_array = np.array(data)
min_index = np.argmin(sales_array)
max_index = np.argmax(sales_array)
min_index, max_index

(2, 5)

In [60]:
data = [100, 150, 200, 250, 300]
sales_array = np.array(data)
new_sale = 350
updated_sales_data = np.append(sales_array, new_sale)
updated_sales_data

array([100, 150, 200, 250, 300, 350])

In [63]:
team_a_scores = np.array([80, 85, 90, 95, 100])
team_b_scores = np.array([70, 75, 80, 85, 90])
all_team_scores = np.concatenate((team_a_scores, team_b_scores))
all_team_scores

array([ 80,  85,  90,  95, 100,  70,  75,  80,  85,  90])

In [65]:
daily_temperatures = [72, 75, 78, 70, 68]
total_temperature = np.sum(daily_temperatures)
total_temperature

363

In [67]:
exam_scores = [85, 90, 88, 92, 87]

average_score = np.mean(exam_scores)

average_score

88.4

In [69]:
age_data = [25, 30, 35, 40, 45]
median_age = np.median(age_data)
median_age

35.0

In [73]:
sales_data = [150, 200, 250, 300, 350]

array = np.array(sales_data)

sliced_array = array[1:5]
sliced_array

array([200, 250, 300, 350])

In [75]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [76]:
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [79]:
demo_array = np.random.rand(10)
demo_array[0:7] = 5
demo_array

array([5.        , 5.        , 5.        , 5.        , 5.        ,
       5.        , 5.        , 0.52146051, 0.13591934, 0.93194744])

In [82]:
demo_array = np.arange(0,10)
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5

In [102]:
data_customer = pd.DataFrame({
    "customer": [101, 102, 103, 104, 101, 102],
    "category": ["cat2", "cat2", "cat1", "cat3", "cat2", "cat2"],
    "important": ["yes", "no", "yes", "yes", "yes", "no"],
    "sales": [123, 52, 214, 663, 203, 212]
})
data_customer

customer category important  sales
0       101     cat2       yes    123
1       102     cat2        no     52
2       103     cat1       yes    214
3       104     cat3       yes    663
4       101     cat2       yes    203
5       102     cat2        no    212

In [87]:
data_customer['category'].value_counts()

category
cat2    2
cat1    1
cat3    1
Name: count, dtype: int64

In [89]:
data_customer.sort_values(by='sales',ascending=False)

customer category important  sales
3       104     cat3       yes    663
2       103     cat1       yes    214
0       101     cat2       yes    123
1       102     cat2        no     52

In [94]:
data_customer.loc[[1,2], ['customer', 'sales']]

customer  sales
1       102     52
2       103    214

In [103]:
data_customer.groupby(['customer'])['sales'].mean()

customer
101    163.0
102    132.0
103    214.0
104    663.0
Name: sales, dtype: float64

In [3]:
np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [4]:
np.arange(start=1, stop=10, step=1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array_1 = np.linspace(0,20,6)
array_1

array([ 0.,  4.,  8., 12., 16., 20.])

In [8]:
array_2 = np.arange(0,20,6)
array_2

array([ 0,  6, 12, 18])

In [10]:
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256], 
                [ 49, 64, 81, 289, 324, 361]])
mean = np.mean(mat)
mean

131.66666666666666

In [16]:
a = np.arange(0,20)
print(a[a>10])
print(a[2:7])

[11 12 13 14 15 16 17 18 19]
[2 3 4 5 6]


In [17]:
np.cos([0, 1, 2, 3, 4]) 

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [19]:
list_1 = [1,2,3] 
list_2 = [4,5,6]
new_list = list_1 + list_2
new_list

[1, 2, 3, 4, 5, 6]

In [20]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
new_array

array([5, 7, 9])

In [22]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat
mat[1] = 5
mat

array([[1, 2, 1],
       [5, 5, 5],
       [1, 8, 9]])

In [23]:
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

21


In [24]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [25]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
np.dot(n1, n2)

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])